name: pinterest_clone_me_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.6.1
  flutter_emoji: ^2.4.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^9.2.0
  dio: ^4.0.4
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.0.0
  lottie: ^1.2.2
  url_launcher: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
